# Generated by Django 5.2.9 on 2025-12-25 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_type', models.CharField(choices=[('SL', 'Sleeper'), ('3A', 'AC 3 Tier'), ('2A', 'AC 2 Tier'), ('1A', 'First Class'), ('CC', 'Chair Car')], max_length=2)),
                ('coach_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('journey_date', models.DateField()),
                ('status', models.CharField(default='available', max_length=20)),
                ('destination_station_sequence', models.PositiveIntegerField(default=0)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='booking.coach')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_seats', to='booking.train')),
            ],
            options={
                'unique_together': {('seat_number', 'coach', 'journey_date', 'train')},
            },
        ),
        migrations.CreateModel(
            name='RouteStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('distance_from_source', models.DecimalField(decimal_places=2, max_digits=6)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stations', to='booking.train')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('train', 'station')},
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_date', models.DateField(default=None)),
                ('rate_per_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('source', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='booking.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='booking.train')),
            ],
            options={
                'unique_together': {('train', 'journey_date')},
            },
        ),
    ]
