# Generated by Django 5.2.9 on 2026-01-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('seat_number', 'coach', 'journey_date', 'train', 'destination_station_sequence')},
        ),
    ]
