# Generated by Django 5.2.9 on 2025-12-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='coach_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
