# Generated by Django 5.2.9 on 2026-01-12 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_seat_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='train',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.train'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed'), ('Waiting', 'Waiting')], default=None, max_length=20),
        ),
    ]
