# Generated by Django 5.2.9 on 2025-12-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_seat_coach_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
    ]
