# Generated by Django 5.2.9 on 2026-01-13 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_train_invoice_status_ticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('refund_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('approved_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('requested_date', models.DateField(auto_now_add=True)),
                ('refund_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('last_process', models.CharField(default='Pending', max_length=100)),
                ('approved_on', models.DateField(auto_now_add=True)),
                ('booking', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='refundRequest', to='booking.booking')),
                ('invoice', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='booking.invoice')),
            ],
        ),
    ]
