# Generated by Django 5.2.9 on 2026-01-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_seat_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.BigIntegerField()),
                ('source_name', models.CharField(max_length=50)),
                ('destination_name', models.CharField(max_length=50)),
                ('journey_date', models.DateField()),
                ('coach_type', models.CharField(max_length=2)),
                ('seat_number', models.IntegerField()),
                ('passenger_name', models.CharField(max_length=50)),
                ('passenger_age', models.IntegerField()),
                ('passenger_gender', models.CharField(max_length=1)),
            ],
        ),
    ]
