# Generated by Django 5.2.9 on 2026-01-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bookings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingToInvoice',
            fields=[
                ('booking_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.BigIntegerField()),
                ('source_name', models.CharField(max_length=50)),
                ('destination_name', models.CharField(max_length=50)),
                ('journey_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('booking_id', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='bookings',
            name='booking_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
