# Generated by Django 5.2.9 on 2026-01-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='refund_date',
            field=models.DateField(default=None),
        ),
    ]
