# Generated by Django 5.2.9 on 2026-01-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_refund_refund_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='approved_on',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
